# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d090f486b6ac47969dca38d6140e1e96"
name = "DO Product Label"
handle = "do-product-label"
application_url = "https://respondent-district-inspections-domestic.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://respondent-district-inspections-domestic.trycloudflare.com/auth/callback", "https://respondent-district-inspections-domestic.trycloudflare.com/auth/shopify/callback", "https://respondent-district-inspections-domestic.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "staging-digitaloutlook.myshopify.com"

